Feature/licenseplate pipeline
sa-mw-dach/dev_demos pull request #5
Opened 2022-06-30 09:39 UTC by Javatar81

Merge pipeline demo into main

2022-06-30 12:41 UTC, manhah requested changes

2022-06-30 12:41 UTC, manhah commented on demos/03_license_plate_pipe/devfile/crw_ai_cpu_pipeline.yaml
> +      branch: feature
This shall be `main` then, right?

2022-06-30 12:41 UTC, manhah commented on demos/03_license_plate_pipe/devfile/crw_ai_cpu_pipeline.yaml
> +  name: crw_ai_cpu_dxkf
Fixed name or rather name pattern?

2022-06-30 12:41 UTC, manhah commented on demos/03_license_plate_pipe/pipeline/github-secret.yaml
> +  secretToken: MTIzNDU2Nw==
This shall be a dummy password.

2022-06-30 12:41 UTC, manhah commented on demos/03_license_plate_pipe/pipeline/licenseplate-pipeline-ext.yaml
> +          value: feature/licenseplate-pipeline
main

2022-06-30 12:41 UTC, manhah commented on demos/03_license_plate_pipe/pipeline/licenseplate-pipeline.yaml
> +          value: feature/licenseplate-pipeline
main

2022-06-30 12:41 UTC, manhah commented on demos/03_license_plate_pipe/setup/README.md
> +#Steps to setup3
typo

2022-06-30 12:41 UTC, manhah commented on demos/03_license_plate_pipe/setup/README.md
> +oc apply -f pipeline/licenseplate-pipeline.yaml
Perhaps you could write some words about the PVC etc. Just quickly describe how to execute the demo.

2022-07-01 07:18 UTC, Javatar81 commented on demos/03_license_plate_pipe/pipeline/github-secret.yaml
> +  secretToken: MTIzNDU2Nw==
It is a dummy password 1234567

2022-07-01 07:20 UTC, Javatar81 commented on demos/03_license_plate_pipe/devfile/crw_ai_cpu_pipeline.yaml
> +      branch: feature
Changed

2022-07-01 07:22 UTC, Javatar81 commented on demos/03_license_plate_pipe/pipeline/licenseplate-pipeline.yaml
> +          value: feature/licenseplate-pipeline
Done

2022-07-01 07:23 UTC, Javatar81 commented on demos/03_license_plate_pipe/pipeline/licenseplate-pipeline-ext.yaml
> +          value: feature/licenseplate-pipeline
Done

2022-07-01 07:24 UTC, Javatar81 commented on demos/03_license_plate_pipe/devfile/crw_ai_cpu_pipeline.yaml
> +  name: crw_ai_cpu_dxkf
```suggestion
  name: crw_ai_cpu_pipeline
```

2022-07-01 07:32 UTC, Javatar81 commented
Addressed all issues. Please review.

2023-10-04 16:12 UTC, manhah approved these changes
Even if it's a little late: Perfect, thanks! :-)

2023-10-04 16:15 UTC, merged